services:
    _defaults:
        public: true

    bitbag.imoje_plugin.action.capture:
        class: BitBag\SyliusImojePlugin\Action\CaptureAction
        arguments:
            - '@bitbag.imoje_plugin.resolver.signature_resolver'
        tags:
            - { name: payum.action, factory: imoje, alias: payum.action.capture }

    bitbag.imoje_plugin.action.status:
        class: BitBag\SyliusImojePlugin\Action\StatusAction
        tags:
            - { name: payum.action, factory: imoje, alias: payum.action.status }

    bitbag.imoje_plugin.action.notify:
        class: BitBag\SyliusImojePlugin\Action\NotifyAction
        arguments:
            - '@request_stack'
            - '@bitbag.imoje_plugin.resolver.signature_resolver'
        tags:
            - { name: payum.action, factory: imoje, alias: payum.action.notify }

    bitbag.imoje_plugin.action.convert_payment:
        class: BitBag\SyliusImojePlugin\Action\ConvertPaymentAction
        tags:
            - { name: payum.action, factory: imoje, alias: payum.action.convert_payment }
