services:
    bitbag.sylius.command_provider.imoje_paywall:
        class: Sylius\Bundle\PaymentBundle\CommandProvider\ActionsCommandProvider
        arguments:
            - !tagged_locator
                tag: bitbag.sylius.command_provider.imoje_paywall
                index_by: 'action'
        tags:
            - name: sylius.payment_request.command_provider
              'gateway-factory': 'imoje_paywall'
    
    bitbag.sylius.command_provider.imoje_paywall.capture:
        class: BitBag\SyliusImojePlugin\CommandProvider\CapturePaymentRequestCommandProvider
        tags:
            -   name: bitbag.sylius.command_provider.imoje_paywall
                action: !php/const Sylius\Component\Payment\Model\PaymentRequestInterface::ACTION_CAPTURE
                
    bitbag.sylius.command_provider.imoje_paywall.status:
        class: BitBag\SyliusImojePlugin\CommandProvider\CapturePaymentRequestCommandProvider
        tags:
            -   name: bitbag.sylius.command_provider.imoje_paywall
                action: !php/const Sylius\Component\Payment\Model\PaymentRequestInterface::ACTION_STATUS
                
    bitbag.sylius.command_provider.imoje_paywall.notify:
        class: BitBag\SyliusImojePlugin\CommandProvider\NotifyPaymentRequestCommandProvider
        tags:
            -   name: bitbag.sylius.command_provider.imoje_paywall
                action: !php/const Sylius\Component\Payment\Model\PaymentRequestInterface::ACTION_NOTIFY
