services:
    bitbag.sylius.command_handlers.imoje_paywall.capture:
        class: BitBag\SyliusImojePlugin\CommandHandler\CapturePaymentRequestHandler
        arguments:
            - '@sylius.provider.payment_request'
            - '@sylius_abstraction.state_machine'
            - '@bitbag.imoje_plugin.resolver.signature_resolver'
            - '@sylius_shop.provider.order_pay.payment_request_pay_url'
        tags:
            - name: messenger.message_handler
              bus: sylius.payment_request.command_bus
              
    bitbag.sylius.command_handlers.imoje_paywall.capture_end:
        class: BitBag\SyliusImojePlugin\CommandHandler\CaptureEndPaymentRequestHandler
        arguments:
            - '@sylius.provider.payment_request'
            - '@sylius_abstraction.state_machine'
            - '@bitbag.sylius_imoje_plugin.processor.payment_transition'
        tags:
            -   name: messenger.message_handler
                bus: sylius.payment_request.command_bus
              
    bitbag.sylius.command_handlers.imoje_paywall.status:
        class: BitBag\SyliusImojePlugin\CommandHandler\StatusPaymentRequestHandler
        arguments:
            - '@sylius.provider.payment_request'
            - '@sylius_abstraction.state_machine'
            - '@bitbag.sylius_imoje_plugin.processor.payment_transition'
        tags:
            -   name: messenger.message_handler
                bus: sylius.payment_request.command_bus
                handles: BitBag\SyliusImojePlugin\Command\StatusPaymentRequest
