services:
    bitbag.imoje_plugin.form.type.gateway_configuration.imoje_paywall:
        class: BitBag\SyliusImojePlugin\Form\Type\ImojeGatewayConfigurationType
        tags:
            - name: sylius.gateway_configuration_type
              type: imoje_paywall
              label: 'bitbag.imoje_plugin.paywall'    
            - name: form.type
